title: Jim Killingsworth

description: >-
    Jim Killingsworth is a computer programmer with over a decade of experience building software systems.

excerpt_separator: <!--excerpt-->

permalink: /posts/:year/:month/:day/:title/

baseurl: /blog

exclude:
    - .vs/
    - Gemfile
    - Gemfile.lock
    - README.md
    - publish.sh

include:
    - _pages

sass:
    style: compressed

jekyll-minifier:
    remove_intertag_spaces: true
    compress_css: false
    compress_javascript: false
